/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rovhome_changer_util_MpegtsParser */

#ifndef _Included_com_rovhome_changer_util_MpegtsParser
#define _Included_com_rovhome_changer_util_MpegtsParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rovhome_changer_util_MpegtsParser
 * Method:    open
 * Signature: (Ljava/lang/String;Lcom/rovhome/changer/util/MpegtsParser/StreamInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_rovhome_changer_util_MpegtsParser_open
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_rovhome_changer_util_MpegtsParser
 * Method:    getStreamElement
 * Signature: (Lcom/rovhome/changer/util/MpegtsParser/AvPacket;)I
 */
JNIEXPORT jint JNICALL Java_com_rovhome_changer_util_MpegtsParser_getStreamElement
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_rovhome_changer_util_MpegtsParser
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rovhome_changer_util_MpegtsParser_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
