/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abrinnovation_utils_HikNetHelper_DataCallback */

#ifndef _Included_com_abrinnovation_utils_HikNetHelper_DataCallback
#define _Included_com_abrinnovation_utils_HikNetHelper_DataCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
