/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abrinnovation_utils_HikNetHelper */

#ifndef _Included_com_abrinnovation_utils_HikNetHelper
#define _Included_com_abrinnovation_utils_HikNetHelper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_abrinnovation_utils_HikNetHelper_NET_DVR_SYSHED
#define com_abrinnovation_utils_HikNetHelper_NET_DVR_SYSHED 1L
#undef com_abrinnovation_utils_HikNetHelper_NET_DVR_STREAMDATA
#define com_abrinnovation_utils_HikNetHelper_NET_DVR_STREAMDATA 2L
#undef com_abrinnovation_utils_HikNetHelper_NET_DVR_AUDIOSTREAMDATA
#define com_abrinnovation_utils_HikNetHelper_NET_DVR_AUDIOSTREAMDATA 3L
#undef com_abrinnovation_utils_HikNetHelper_NET_DVR_STD_VIDEODATA
#define com_abrinnovation_utils_HikNetHelper_NET_DVR_STD_VIDEODATA 4L
#undef com_abrinnovation_utils_HikNetHelper_NET_DVR_STD_AUDIODATA
#define com_abrinnovation_utils_HikNetHelper_NET_DVR_STD_AUDIODATA 5L
#undef com_abrinnovation_utils_HikNetHelper_NET_DVR_SDP
#define com_abrinnovation_utils_HikNetHelper_NET_DVR_SDP 6L
#undef com_abrinnovation_utils_HikNetHelper_NET_DVR_CHANGE_FORWARD
#define com_abrinnovation_utils_HikNetHelper_NET_DVR_CHANGE_FORWARD 10L
#undef com_abrinnovation_utils_HikNetHelper_NET_DVR_CHANGE_REVERSE
#define com_abrinnovation_utils_HikNetHelper_NET_DVR_CHANGE_REVERSE 11L
#undef com_abrinnovation_utils_HikNetHelper_NET_DVR_PRIVATE_DATA
#define com_abrinnovation_utils_HikNetHelper_NET_DVR_PRIVATE_DATA 112L
/*
 * Class:     com_abrinnovation_utils_HikNetHelper
 * Method:    login
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_abrinnovation_utils_HikNetHelper_login
  (JNIEnv *, jclass, jstring, jint, jstring, jstring);

/*
 * Class:     com_abrinnovation_utils_HikNetHelper
 * Method:    beginRealplay
 * Signature: (Lcom/abrinnovation/utils/HikNetHelper/DataCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_abrinnovation_utils_HikNetHelper_beginRealplay
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_abrinnovation_utils_HikNetHelper
 * Method:    endRealplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abrinnovation_utils_HikNetHelper_endRealplay
  (JNIEnv *, jclass);

/*
 * Class:     com_abrinnovation_utils_HikNetHelper
 * Method:    logout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abrinnovation_utils_HikNetHelper_logout
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
